import { Banknote, Building2, Smartphone } from "lucide-react";
import type { Account, AccountTransaction } from "./types";

export const accounts: Account[] = [
  {
    id: 1,
    name: "BCA - Main",
    type: "bank",
    balance: 4_500_000,
    accountNumber: "****1234",
    icon: Building2,
    color: "bg-blue-500",
    transactions: 45,
  },
  {
    id: 2,
    name: "Mandiri - Saving",
    type: "bank",
    balance: 12_500_000,
    accountNumber: "****5678",
    icon: Building2,
    color: "bg-yellow-500",
    transactions: 32,
  },
  {
    id: 3,
    name: "GoPay",
    type: "e-wallet",
    balance: 385_000,
    accountNumber: "0812****890",
    icon: Smartphone,
    color: "bg-green-500",
    transactions: 78,
  },
  {
    id: 4,
    name: "OVO",
    type: "e-wallet",
    balance: 250_000,
    accountNumber: "0812****890",
    icon: Smartphone,
    color: "bg-purple-500",
    transactions: 56,
  },
  {
    id: 5,
    name: "Cash",
    type: "cash",
    balance: 1_500_000,
    accountNumber: "-",
    icon: Banknote,
    color: "bg-emerald-500",
    transactions: 23,
  },
];

export const accountTransactions: AccountTransaction[] = [
  {
    id: 1,
    accountId: 1,
    title: "Gaji Bulanan",
    amount: 8_000_000,
    type: "income",
    date: "2025-12-01",
  },
  {
    id: 2,
    accountId: 1,
    title: "Belanja Bulanan",
    amount: -850_000,
    type: "expense",
    date: "2025-12-05",
  },
  {
    id: 3,
    accountId: 1,
    title: "Listrik & Air",
    amount: -320_000,
    type: "expense",
    date: "2025-12-03",
  },
  {
    id: 4,
    accountId: 3,
    title: "Grab ke kantor",
    amount: -75_000,
    type: "expense",
    date: "2025-12-06",
  },
  {
    id: 5,
    accountId: 3,
    title: "Top Up GoPay",
    amount: 500_000,
    type: "income",
    date: "2025-12-04",
  },
  {
    id: 6,
    accountId: 5,
    title: "Kopi & Snack",
    amount: -45_000,
    type: "expense",
    date: "2025-12-06",
  },
  {
    id: 7,
    accountId: 5,
    title: "Makan Siang",
    amount: -125_000,
    type: "expense",
    date: "2025-12-07",
  },
  {
    id: 8,
    accountId: 2,
    title: "Transfer dari BCA",
    amount: 5_000_000,
    type: "income",
    date: "2025-12-02",
  },
];
