import { Home, ShoppingBag, Utensils, Film, TrendingUp } from "lucide-react";
import type { Group, GroupMember, GroupTransaction, UserData } from "./types";

export const userData: UserData = {
  username: "Budi Santoso",
  email: "budi@email.com",
  userId: 1,
};

export const groups: Group[] = [
  {
    id: 1,
    name: "Kost Bersama",
    description: "Pengeluaran kost dan utilitas bersama",
    createdBy: 1,
    memberCount: 4,
    totalExpense: 2500000,
    totalIncome: 3000000,
    createdAt: "2025-11-01",
  },
  {
    id: 2,
    name: "Liburan Bali 2025",
    description: "Budget dan pengeluaran liburan ke Bali",
    createdBy: 1,
    memberCount: 5,
    totalExpense: 8500000,
    totalIncome: 10000000,
    createdAt: "2025-10-15",
  },
  {
    id: 3,
    name: "Keluarga",
    description: "Pengeluaran keluarga bulanan",
    createdBy: 2,
    memberCount: 3,
    totalExpense: 5200000,
    totalIncome: 8000000,
    createdAt: "2025-09-01",
  },
  {
    id: 4,
    name: "Project Freelance",
    description: "Budget project web development",
    createdBy: 1,
    memberCount: 2,
    totalExpense: 1200000,
    totalIncome: 5000000,
    createdAt: "2025-11-20",
  },
];

export const groupMembers: GroupMember[] = [
  {
    id: 1,
    groupId: 1,
    userId: 1,
    username: "Budi Santoso",
    email: "budi@email.com",
    role: "admin",
    joinedAt: "2025-11-01",
  },
  {
    id: 2,
    groupId: 1,
    userId: 2,
    username: "Andi Wijaya",
    email: "andi@email.com",
    role: "member",
    joinedAt: "2025-11-02",
  },
  {
    id: 3,
    groupId: 1,
    userId: 3,
    username: "Citra Dewi",
    email: "citra@email.com",
    role: "member",
    joinedAt: "2025-11-03",
  },
  {
    id: 4,
    groupId: 1,
    userId: 4,
    username: "Doni Pratama",
    email: "doni@email.com",
    role: "member",
    joinedAt: "2025-11-05",
  },
  {
    id: 5,
    groupId: 2,
    userId: 1,
    username: "Budi Santoso",
    email: "budi@email.com",
    role: "admin",
    joinedAt: "2025-10-15",
  },
  {
    id: 6,
    groupId: 2,
    userId: 5,
    username: "Eka Putri",
    email: "eka@email.com",
    role: "member",
    joinedAt: "2025-10-16",
  },
  {
    id: 7,
    groupId: 2,
    userId: 6,
    username: "Fajar Ramadan",
    email: "fajar@email.com",
    role: "member",
    joinedAt: "2025-10-16",
  },
  {
    id: 8,
    groupId: 2,
    userId: 7,
    username: "Gita Sari",
    email: "gita@email.com",
    role: "member",
    joinedAt: "2025-10-17",
  },
  {
    id: 9,
    groupId: 2,
    userId: 8,
    username: "Hadi Kusuma",
    email: "hadi@email.com",
    role: "member",
    joinedAt: "2025-10-18",
  },
  {
    id: 10,
    groupId: 3,
    userId: 2,
    username: "Andi Wijaya",
    email: "andi@email.com",
    role: "admin",
    joinedAt: "2025-09-01",
  },
  {
    id: 11,
    groupId: 3,
    userId: 1,
    username: "Budi Santoso",
    email: "budi@email.com",
    role: "member",
    joinedAt: "2025-09-02",
  },
  {
    id: 12,
    groupId: 3,
    userId: 9,
    username: "Indah Permata",
    email: "indah@email.com",
    role: "member",
    joinedAt: "2025-09-03",
  },
  {
    id: 13,
    groupId: 4,
    userId: 1,
    username: "Budi Santoso",
    email: "budi@email.com",
    role: "admin",
    joinedAt: "2025-11-20",
  },
  {
    id: 14,
    groupId: 4,
    userId: 10,
    username: "Joko Widodo",
    email: "joko@email.com",
    role: "member",
    joinedAt: "2025-11-21",
  },
];

export const groupTransactions: GroupTransaction[] = [
  {
    id: 1,
    groupId: 1,
    userId: 1,
    username: "Budi Santoso",
    title: "Bayar Kost Bulan Desember",
    amount: -1500000,
    type: "expense",
    category: "Rent",
    icon: Home,
    color: "text-blue-600",
    date: "2025-12-01",
    description: "Kost 4 orang @ 375rb",
  },
  {
    id: 2,
    groupId: 1,
    userId: 2,
    username: "Andi Wijaya",
    title: "Listrik & Air",
    amount: -500000,
    type: "expense",
    category: "Bills",
    icon: Home,
    color: "text-blue-600",
    date: "2025-12-03",
    description: "Tagihan utilitas",
  },
  {
    id: 3,
    groupId: 1,
    userId: 3,
    username: "Citra Dewi",
    title: "Belanja Bulanan",
    amount: -500000,
    type: "expense",
    category: "Shopping",
    icon: ShoppingBag,
    color: "text-purple-600",
    date: "2025-12-05",
    description: "Belanja kebutuhan bersama",
  },
  {
    id: 4,
    groupId: 1,
    userId: 1,
    username: "Budi Santoso",
    title: "Iuran Bersama",
    amount: 3000000,
    type: "income",
    category: "Payment",
    icon: TrendingUp,
    color: "text-emerald-600",
    date: "2025-11-30",
    description: "Iuran dari semua anggota",
  },

  {
    id: 5,
    groupId: 2,
    userId: 1,
    username: "Budi Santoso",
    title: "Tiket Pesawat",
    amount: -4500000,
    type: "expense",
    category: "Transport",
    icon: Film,
    color: "text-red-600",
    date: "2025-11-25",
    description: "Tiket PP 5 orang",
  },
  {
    id: 6,
    groupId: 2,
    userId: 5,
    username: "Eka Putri",
    title: "Hotel 3 Malam",
    amount: -2400000,
    type: "expense",
    category: "Accommodation",
    icon: Home,
    color: "text-blue-600",
    date: "2025-11-26",
    description: "2 kamar x 3 malam",
  },
  {
    id: 7,
    groupId: 2,
    userId: 6,
    username: "Fajar Ramadan",
    title: "Makan & Jajan",
    amount: -1600000,
    type: "expense",
    category: "Food",
    icon: Utensils,
    color: "text-orange-600",
    date: "2025-12-01",
    description: "Total selama 3 hari",
  },
  {
    id: 8,
    groupId: 2,
    userId: 1,
    username: "Budi Santoso",
    title: "Patungan Liburan",
    amount: 10000000,
    type: "income",
    category: "Payment",
    icon: TrendingUp,
    color: "text-emerald-600",
    date: "2025-11-20",
    description: "Uang patungan 5 orang @ 2jt",
  },

  {
    id: 9,
    groupId: 3,
    userId: 2,
    username: "Andi Wijaya",
    title: "Belanja Dapur",
    amount: -1500000,
    type: "expense",
    category: "Food",
    icon: ShoppingBag,
    color: "text-purple-600",
    date: "2025-12-01",
    description: "Belanja bulanan",
  },
  {
    id: 10,
    groupId: 3,
    userId: 1,
    username: "Budi Santoso",
    title: "Bayar Sekolah Anak",
    amount: -2500000,
    type: "expense",
    category: "Education",
    icon: Home,
    color: "text-blue-600",
    date: "2025-12-02",
    description: "SPP bulan Desember",
  },

  {
    id: 11,
    groupId: 4,
    userId: 1,
    username: "Budi Santoso",
    title: "Bayar Hosting",
    amount: -200000,
    type: "expense",
    category: "Bills",
    icon: Home,
    color: "text-blue-600",
    date: "2025-12-01",
    description: "Hosting 1 tahun",
  },
  {
    id: 12,
    groupId: 4,
    userId: 10,
    username: "Joko Widodo",
    title: "Domain & SSL",
    amount: -300000,
    type: "expense",
    category: "Bills",
    icon: Home,
    color: "text-blue-600",
    date: "2025-12-02",
    description: "Domain + SSL certificate",
  },
];
